import React,{useState}from'react';import{View,Text,TouchableOpacity,ActivityIndicator,RefreshControl,ScrollView,Modal,TextInput}from'react-native';import{useSOSLogs,useEmergencyContacts,useIncidents}from'../hooks/useSafety';import{Ionicons}from'@expo/vector-icons';
function ECM({v,o,ci,si}:{v:boolean;o:()=>void;ci:string;si:string}){const{add}=useEmergencyContacts(ci);const[n,setN]=useState('');const[r,setR]=useState('');const[p,setP]=useState('');const[e,setE]=useState('');const[sv,setS]=useState(false);
const save=async()=>{if(!n||!p)return;setS(true);try{await add({child_id:ci,institution_id:si,contact_name:n,relationship:r||'Other',phone:p,email:e||null});o();}catch(e){}finally{setS(false);}};
return(<Modal visible={v}animationType="slide"transparent onRequestClose={o}><View style={{flex:1,backgroundColor:'rgba(0,0,0,0.5)',justifyContent:'flex-end'}}><View style={{backgroundColor:'#fff',borderTopLeftRadius:20,borderTopRightRadius:20,padding:20}}><Text style={{fontSize:18,fontWeight:'700',marginBottom:14}}>Add Contact</Text><TextInput placeholder="Name"value={n}onChangeText={setN}style={{backgroundColor:'#F3F4F6',borderRadius:12,padding:12,marginBottom:10,fontSize:14}}/><TextInput placeholder="Relationship"value={r}onChangeText={setR}style={{backgroundColor:'#F3F4F6',borderRadius:12,padding:12,marginBottom:10,fontSize:14}}/><TextInput placeholder="Phone"keyboardType="phone-pad"value={p}onChangeText={setP}style={{backgroundColor:'#F3F4F6',borderRadius:12,padding:12,marginBottom:10,fontSize:14}}/><TextInput placeholder="Email (opt)"keyboardType="email-address"value={e}onChangeText={setE}style={{backgroundColor:'#F3F4F6',borderRadius:12,padding:12,marginBottom:16,fontSize:14}}/><TouchableOpacity onPress={save}disabled={sv}style={{backgroundColor:sv?'#D1D5DB':'#3B82F6',borderRadius:14,padding:14,alignItems:'center'}}><Text style={{color:'#fff',fontWeight:'700',fontSize:15}}>{sv?'Saving...':'Add'}</Text></TouchableOpacity></View></View></Modal>);}
export default function ParentSafetyScreen({childId,institutionId}:{childId:string;institutionId:string}){const[tab,setTab]=useState<'sos'|'contacts'|'incidents'>('sos');const[rf,setRf]=useState(false);const[ecm,setEcm]=useState(false);const[pl,setPl]=useState(false);
const{logs,sl,se,rs,trigger}=useSOSLogs(institutionId,{childId});const{contacts,cl,ce,rc}=useEmergencyContacts(childId);const{incidents,il,ie,ri}=useIncidents(institutionId,{childId});
const ra=async()=>{setRf(true);await Promise.all([rs(),rc(),ri()]);setRf(false);};
const panic=async()=>{setPl(true);try{await trigger(childId,institutionId);}catch(e){}finally{setPl(false);}};
const tabs=[{k:'sos',l:'SOS',i:'alert-circle'},{k:'contacts',l:'Contacts',i:'people'},{k:'incidents',l:'Incidents',i:'warning'}];
if(sl&&logs.length===0)return<View style={{flex:1,justifyContent:'center',alignItems:'center'}}><ActivityIndicator size="large"color="#EF4444"/></View>;
if(se&&logs.length===0)return<View style={{flex:1,justifyContent:'center',alignItems:'center',padding:20}}><Ionicons name="warning"size={40}color="#EF4444"/><Text style={{marginTop:12,color:'#EF4444'}}>{se}</Text><TouchableOpacity onPress={ra}style={{marginTop:16,backgroundColor:'#EF4444',paddingHorizontal:20,paddingVertical:10,borderRadius:20}}><Text style={{color:'#fff',fontWeight:'600'}}>Retry</Text></TouchableOpacity></View>;
return(<View style={{flex:1,backgroundColor:'#F9FAFB'}}><View style={{backgroundColor:'#fff',paddingHorizontal:16,paddingTop:50,paddingBottom:12}}><Text style={{fontSize:20,fontWeight:'800',color:'#111827'}}>Child Safety</Text><Text style={{fontSize:13,color:'#6B7280',marginTop:2}}>Parent Panel</Text></View><View style={{backgroundColor:'#fff',padding:16,alignItems:'center'}}><TouchableOpacity onPress={panic}disabled={pl}style={{width:120,height:120,borderRadius:60,backgroundColor:pl?'#FCA5A5':'#EF4444',justifyContent:'center',alignItems:'center',shadowColor:'#EF4444',shadowOffset:{width:0,height:4},shadowOpacity:0.3,shadowRadius:8,elevation:6}}><Ionicons name="alert"size={36}color="#fff"/><Text style={{color:'#fff',fontWeight:'800',fontSize:14,marginTop:4}}>{pl?'SENDING...':'SOS'}</Text></TouchableOpacity><Text style={{fontSize:12,color:'#9CA3AF',marginTop:8}}>Press in emergency</Text></View><View style={{flexDirection:'row',backgroundColor:'#fff',paddingHorizontal:8,paddingBottom:8,borderBottomWidth:1,borderColor:'#F3F4F6'}}>{tabs.map(t=><TouchableOpacity key={t.k}onPress={()=>setTab(t.k as any)}style={{flex:1,alignItems:'center',paddingVertical:8,borderBottomWidth:2,borderColor:tab===t.k?'#EF4444':'transparent'}}><Ionicons name={t.i}size={18}color={tab===t.k?'#EF4444':'#9CA3AF'}/><Text style={{fontSize:11,fontWeight:'600',color:tab===t.k?'#EF4444':'#9CA3AF',marginTop:2}}>{t.l}</Text></TouchableOpacity>)}</View>
<ScrollView refreshControl={<RefreshControl refreshing={rf}onRefresh={ra}/>}contentContainerStyle={{padding:12}}>
{tab==='sos'&&<>{logs.map(s=><View key={s.id}style={{backgroundColor:'#fff',borderRadius:12,padding:14,marginBottom:8,borderLeftWidth:4,borderColor:s.status==='active'?'#EF4444':'#10B981'}}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><Text style={{fontWeight:'700',fontSize:14}}>SOS</Text><View style={{backgroundColor:s.status==='active'?'#FEE2E2':'#D1FAE5',paddingHorizontal:8,paddingVertical:3,borderRadius:10}}><Text style={{fontSize:11,fontWeight:'700',color:s.status==='active'?'#DC2626':'#059669'}}>{s.status.toUpperCase()}</Text></View></View><Text style={{fontSize:12,color:'#6B7280',marginTop:4}}>{s.reason||'Button pressed'} · {new Date(s.created_at).toLocaleString()}</Text>{s.lat&&<Text style={{fontSize:11,color:'#9CA3AF',marginTop:2}}>{s.lat.toFixed(5)},{s.lng.toFixed(5)}</Text>}</View>)}{logs.length===0&&!sl&&<Text style={{textAlign:'center',color:'#9CA3AF',marginVertical:20}}>No SOS history</Text>}</>}
{tab==='contacts'&&<><TouchableOpacity onPress={()=>setEcm(true)}style={{backgroundColor:'#3B82F6',borderRadius:14,padding:14,alignItems:'center',marginBottom:12}}><Text style={{color:'#fff',fontWeight:'700',fontSize:15}}>+ Add Contact</Text></TouchableOpacity>{cl&&contacts.length===0&&<ActivityIndicator style={{marginVertical:20}}/>}{ce&&<Text style={{color:'#EF4444',textAlign:'center'}}>{ce}</Text>}{contacts.map(c=><View key={c.id}style={{backgroundColor:'#fff',borderRadius:12,padding:14,marginBottom:8,flexDirection:'row',alignItems:'center'}}><View style={{width:44,height:44,borderRadius:22,backgroundColor:c.is_primary?'#D1FAE5':'#F3F4F6',justifyContent:'center',alignItems:'center'}}><Ionicons name={c.is_primary?'star':'person'}size={20}color={c.is_primary?'#059669':'#6B7280'}/></View><View style={{flex:1,marginLeft:12}}><Text style={{fontWeight:'700',fontSize:14}}>{c.contact_name}</Text><Text style={{fontSize:12,color:'#6B7280'}}>{c.relationship} · {c.phone}</Text>{c.can_pickup&&<Text style={{fontSize:11,color:'#3B82F6',marginTop:2}}>Pickup authorized</Text>}</View>{c.is_primary&&<View style={{backgroundColor:'#D1FAE5',paddingHorizontal:8,paddingVertical:3,borderRadius:10}}><Text style={{fontSize:10,fontWeight:'700',color:'#059669'}}>PRIMARY</Text></View>}</View>)}{contacts.length===0&&!cl&&<Text style={{textAlign:'center',color:'#9CA3AF',marginVertical:20}}>No contacts</Text>}</>}
{tab==='incidents'&&<>{il&&incidents.length===0&&<ActivityIndicator style={{marginVertical:20}}/>}{ie&&<Text style={{color:'#EF4444',textAlign:'center'}}>{ie}</Text>}{incidents.map(i=><View key={i.id}style={{backgroundColor:'#fff',borderRadius:12,padding:14,marginBottom:8,borderLeftWidth:4,borderColor:i.severity==='critical'?'#DC2626':i.severity==='high'?'#F59E0B':'#3B82F6'}}><Text style={{fontWeight:'700',fontSize:14,textTransform:'capitalize'}}>{i.incident_type.replace('_',' ')}</Text><Text style={{fontSize:12,color:'#6B7280',marginTop:4}}>{i.description}</Text><Text style={{fontSize:11,color:'#9CA3AF',marginTop:2}}>{i.severity} · {i.status} · {new Date(i.created_at).toLocaleDateString()}</Text></View>)}{incidents.length===0&&!il&&<Text style={{textAlign:'center',color:'#9CA3AF',marginVertical:20}}>No incidents</Text>}</>}
</ScrollView><ECM v={ecm}o={()=>setEcm(false)}ci={childId}si={institutionId}/></View>);}
