import React,{useState}from'react';import{View,Text,TouchableOpacity,ActivityIndicator,RefreshControl,ScrollView,Modal,TextInput}from'react-native';import{useContentLibrary}from'../hooks/useTeacherEconomy';import{Ionicons}from'@expo/vector-icons';
export default function ResourceLibraryScreen({institutionId,teacherId}:{institutionId:string;teacherId:string}){const[um,setUm]=useState(false);const[rf,setRf]=useState(false);const{content,loading,error,refresh,upload}=useContentLibrary(institutionId);
const[ti,setTi]=useState('');const[ty,setTy]=useState('pdf');const[url,setU]=useState('');const[sub,setS]=useState('');const[sv,setSv]=useState(false);
const ra=async()=>{setRf(true);await refresh();setRf(false);};
const save=async()=>{if(!ti||!url)return;setSv(true);try{await upload({institution_id:institutionId,uploader_id:teacherId,title:ti,content_type:ty,url,subject_id:sub||null});setUm(false);setTi('');setU('');}catch(e){}finally{setSv(false);}};
const types=['pdf','video','audio','image','link','doc'];
if(loading&&!content.length)return<View style={{flex:1,justifyContent:'center',alignItems:'center'}}><ActivityIndicator size="large"color="#3B82F6"/></View>;
if(error&&!content.length)return<View style={{flex:1,justifyContent:'center',alignItems:'center',padding:20}}><Ionicons name="warning"size={40}color="#EF4444"/><Text style={{marginTop:12,color:'#EF4444'}}>{error}</Text><TouchableOpacity onPress={ra}style={{marginTop:16,backgroundColor:'#3B82F6',paddingHorizontal:20,paddingVertical:10,borderRadius:20}}><Text style={{color:'#fff',fontWeight:'600'}}>Retry</Text></TouchableOpacity></View>;
return(<View style={{flex:1,backgroundColor:'#F9FAFB'}}><View style={{backgroundColor:'#fff',paddingHorizontal:16,paddingTop:50,paddingBottom:12}}><Text style={{fontSize:20,fontWeight:'800',color:'#111827'}}>Resources</Text><Text style={{fontSize:13,color:'#6B7280',marginTop:2}}>Learning materials</Text></View><TouchableOpacity onPress={()=>setUm(true)}style={{backgroundColor:'#3B82F6',borderRadius:14,padding:14,alignItems:'center',margin:12}}><Text style={{color:'#fff',fontWeight:'700',fontSize:15}}>+ Upload Resource</Text></TouchableOpacity><ScrollView refreshControl={<RefreshControl refreshing={rf}onRefresh={ra}/>}contentContainerStyle={{padding:12}}>{content.map((c: any) =><View key={c.id}style={{backgroundColor:'#fff',borderRadius:12,padding:14,marginBottom:8}}><View style={{flexDirection:'row',alignItems:'center'}}><View style={{width:44,height:44,borderRadius:22,backgroundColor:'#DBEAFE',justifyContent:'center',alignItems:'center'}}><Ionicons name={c.content_type==='video'?'videocam':c.content_type==='audio'?'musical-notes':'document-text'}size={22}color="#3B82F6"/></View><View style={{flex:1,marginLeft:12}}><Text style={{fontWeight:'700',fontSize:14}}numberOfLines={1}>{c.title}</Text><Text style={{fontSize:12,color:'#6B7280',marginTop:2}}>{c.content_type} · {c.subject?.name||'General'} · {c.uploader?.user?.full_name||'Unknown'}</Text></View></View></View>)}{content.length===0&&!loading&&<Text style={{textAlign:'center',color:'#9CA3AF',marginVertical:20}}>No resources yet</Text>}</ScrollView><Modal visible={um}animationType="slide"transparent onRequestClose={()=>setUm(false)}><View style={{flex:1,backgroundColor:'rgba(0,0,0,0.5)',justifyContent:'flex-end'}}><View style={{backgroundColor:'#fff',borderTopLeftRadius:20,borderTopRightRadius:20,padding:20}}><Text style={{fontSize:18,fontWeight:'700',marginBottom:14}}>Upload Resource</Text><TextInput placeholder="Title"value={ti}onChangeText={setTi}style={{backgroundColor:'#F3F4F6',borderRadius:12,padding:12,marginBottom:10,fontSize:14}}/><TextInput placeholder="URL"value={url}onChangeText={setU}style={{backgroundColor:'#F3F4F6',borderRadius:12,padding:12,marginBottom:10,fontSize:14}}/><Text style={{fontSize:13,color:'#6B7280',marginBottom:8}}>Type</Text><View style={{flexDirection:'row',flexWrap:'wrap',marginBottom:10}}>{types.map((t: any) =><TouchableOpacity key={t}onPress={()=>setTy(t)}style={{backgroundColor:ty===t?'#3B82F6':'#F3F4F6',paddingHorizontal:12,paddingVertical:6,borderRadius:16,marginRight:8,marginBottom:8}}><Text style={{fontSize:12,fontWeight:'600',color:ty===t?'#fff':'#374151',textTransform:'capitalize'}}>{t}</Text></TouchableOpacity>)}</View><TouchableOpacity onPress={save}disabled={sv}style={{backgroundColor:sv?'#D1D5DB':'#3B82F6',borderRadius:14,padding:14,alignItems:'center'}}><Text style={{color:'#fff',fontWeight:'700',fontSize:15}}>{sv?'Uploading...':'Upload'}</Text></TouchableOpacity></View></View></Modal></View>);}
