// @ts-nocheck
// Append to lib/asis-cse/asis-cse-constants.ts
export const COUPLING = 0.618;
export const UNDERSTANDING_DEPTH_LIMIT = 5;
export const WISDOM_CONFIDENCE_THRESHOLD = 0.75;
export const REASONING_CONFIDENCE_THRESHOLD = 0.6;
export const REFLECTION_CONFIDENCE_THRESHOLD = 0.5;
export const SECURITY_CONFIDENCE_THRESHOLD = 0.8;
export const TRUST_DECAY_RATE = 0.01;
export const PLANNING_MAX_TASKS = 20;
export const SIMULATION_DEPTH_LIMIT = 3;
export const SIMULATION_BRANCHING_FACTOR = 3;
export const LEARNING_CONFIDENCE_THRESHOLD = 0.5;
export const METRICS_CONFIDENCE_THRESHOLD = 0.5;
export const COLLECTIVE_CONFIDENCE_THRESHOLD = 0.5;
export const EVOLUTION_CONFIDENCE_THRESHOLD = 0.5;
export const KNOWLEDGE_CONFIDENCE_THRESHOLD = 0.5;
export const DECISION_CONFIDENCE_THRESHOLD = 0.5;
export const ADAPTATION_CONFIDENCE_THRESHOLD = 0.5;
export const ACTION_CONFIDENCE_THRESHOLD = 0.5;
export const FEEDBACK_CONFIDENCE_THRESHOLD = 0.5;
