export const Colors = {
  primary: "#2563eb" as const,
  primaryDark: "#1d4ed8" as const,
  primaryLight: "#3b82f6" as const,
  primaryForeground: "#ffffff" as const,
  success: "#22c55e" as const,
  successLight: "#dcfce7" as const,
  warning: "#f59e0b" as const,
  warningLight: "#fef3c7" as const,
  danger: "#ef4444" as const,
  dangerLight: "#fee2e2" as const,
  info: "#0ea5e9" as const,
  infoLight: "#e0f2fe" as const,
  secondary: "#e5e7eb" as const,
  text: "#1f2937" as const,
  textSecondary: "#6b7280" as const,
  background: "#ffffff" as const,
  backgroundSecondary: "#f3f4f6" as const,
  border: "#e5e7eb" as const,
  card: "#ffffff" as const,
  muted: "#9ca3af" as const,
  dark: {
    primary: "#3b82f6",
    text: "#f9fafb",
    textSecondary: "#9ca3af",
    background: "#111827",
    backgroundSecondary: "#1f2937",
    border: "#374151",
    card: "#1f2937",
  },
} as const;

export type ColorType = typeof Colors;
