export interface CodeSnippet {
  language: string;
  code: string;
  description: string;
  timestamp: number;
}

export class CodeTool {
  private snippets: CodeSnippet[] = [];

  generateCode(description: string, language: string = 'typescript'): CodeSnippet {
    // Template-based code generation for common patterns
    let code = '';
    const desc = description.toLowerCase();

    if (desc.includes('supabase') && desc.includes('query')) {
      code = `import { supabase } from '@/lib/supabase';

async function fetchData() {
  const { data, error } = await supabase
    .from('your_table')
    .select('*')
    .limit(10);

  if (error) throw error;
  return data;
}`;
    } else if (desc.includes('react') && desc.includes('component')) {
      code = `import React from 'react';
import { View, Text, StyleSheet } from 'react-native';

export function MyComponent() {
  return (
    <View style={styles.container}>
      <Text>Hello from MyComponent</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { padding: 16 }
});`;
    } else if (desc.includes('hook')) {
      code = `import { useState, useEffect } from 'react';

export function useCustomHook() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchData().then(result => {
      setData(result);
      setLoading(false);
    });
  }, []);

  return { data, loading };
}`;
    } else if (desc.includes('sql') || desc.includes('table')) {
      code = `-- Create a new table
CREATE TABLE example_table (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add RLS policy
ALTER TABLE example_table ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own data"
  ON example_table
  FOR SELECT
  USING (auth.uid() = user_id);`;
    } else {
      code = `// ${description}
// Generated by ASIS Code Tool

function solution() {
  // TODO: Implement based on requirements
  console.log('Implementing: ${description}');
  return null;
}

export { solution };`;
    }

    const snippet: CodeSnippet = {
      language,
      code,
      description,
      timestamp: Date.now()
    };

    this.snippets.push(snippet);
    return snippet;
  }

  explainCode(code: string): string {
    // Simple explanation based on patterns
    const lines = code.split('\n');
    const explanations: string[] = [];

    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed.startsWith('import')) {
        explanations.push(`📦 Imports: ${trimmed}`);
      } else if (trimmed.includes('function') || trimmed.includes('=>')) {
        explanations.push(`⚙️ Function: ${trimmed.slice(0, 60)}...`);
      } else if (trimmed.includes('return')) {
        explanations.push(`↩️ Returns: ${trimmed}`);
      } else if (trimmed.includes('useState') || trimmed.includes('useEffect')) {
        explanations.push(`🪝 React Hook: ${trimmed.slice(0, 50)}...`);
      }
    }

    return explanations.join('\n') || 'Code explanation not available for this snippet.';
  }

  getSnippets(): CodeSnippet[] {
    return [...this.snippets];
  }
}

export const codeTool = new CodeTool();
