// lib/mtaa/appstore/unified-registry.ts
// MTAA OS App Registry — Auto-generated clean version (civic archived)

export const appRegistry = {
  // ─── CORE OS ───
  wallet: {
    id: 'wallet', name: 'Wallet', version: '3.0.0',
    description: 'MTAA Wallet — Send, receive, and manage money.',
    shortDescription: 'Digital wallet and payments.',
    category: 'os', icon: 'wallet-outline', route: '/(os)/wallet',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: true,
    color: '#007AFF', rating: 4.8, reviewCount: 5000, downloadCount: 100000,
    sizeMB: 15, permissions: ['wallet_read', 'wallet_write', 'notifications'],
    tags: ['payments', 'money', 'finance'],
  },
  health: {
    id: 'health', name: 'Health', version: '2.0.0',
    description: 'Personal health records, appointments, and telemedicine.',
    shortDescription: 'Health records & telemedicine.',
    category: 'os', icon: 'heart-outline', route: '/(os)/health',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: true,
    color: '#34C759', rating: 4.6, reviewCount: 3200, downloadCount: 75000,
    sizeMB: 20, permissions: ['health_read', 'health_write', 'notifications'],
    tags: ['health', 'medical', 'doctor'],
  },
  settings: {
    id: 'settings', name: 'Settings', version: '1.0.0',
    description: 'OS settings and preferences.',
    shortDescription: 'System settings.',
    category: 'os', icon: 'settings-outline', route: '/(os)/settings',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: false,
    color: '#8E8E93', rating: 4.5, reviewCount: 1000, downloadCount: 50000,
    sizeMB: 5, permissions: [],
    tags: ['settings', 'system'],
  },
  profile: {
    id: 'profile', name: 'Profile', version: '2.0.0',
    description: 'Your MTAA identity and profile.',
    shortDescription: 'User profile and identity.',
    category: 'os', icon: 'person-outline', route: '/(os)/profile',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: true,
    color: '#5856D6', rating: 4.4, reviewCount: 2000, downloadCount: 60000,
    sizeMB: 8, permissions: ['identity', 'profile_read'],
    tags: ['profile', 'identity'],
  },
  appstore: {
    id: 'appstore', name: 'App Store', version: '1.0.0',
    description: 'Discover and install MTAA apps.',
    shortDescription: 'App marketplace.',
    category: 'os', icon: 'apps-outline', route: '/(os)/appstore',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: false,
    color: '#007AFF', rating: 4.7, reviewCount: 1500, downloadCount: 80000,
    sizeMB: 10, permissions: [],
    tags: ['apps', 'store', 'marketplace'],
  },

  // ─── FINANCE ───
  binance: {
    id: 'binance', name: 'Binance', version: '1.1.0',
    description: 'Crypto trading and wallet. Buy, sell, and trade Bitcoin, Ethereum, and other cryptocurrencies.',
    shortDescription: 'Crypto trading and wallet.',
    category: 'finance', icon: 'trending-up-outline', route: '/(finance)/binance',
    developer: 'Binance', isOSApp: false, requiresAuth: true,
    color: '#F0B90B', rating: 4.5, reviewCount: 1200, downloadCount: 35000,
    sizeMB: 25, permissions: ['wallet_read', 'wallet_write'],
    tags: ['crypto', 'bitcoin', 'trading'],
  },
  credit: {
    id: 'credit', name: 'Credit', version: '1.0.0',
    description: 'Loans and credit services. Apply for personal loans, business credit, and microfinance.',
    shortDescription: 'Loans and credit services.',
    category: 'finance', icon: 'card-outline', route: '/(finance)/credit',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: true,
    color: '#10B981', rating: 4.0, reviewCount: 210, downloadCount: 9000,
    sizeMB: 10, permissions: ['wallet_read', 'identity', 'credit_check'],
    tags: ['loans', 'credit', 'microfinance'],
  },
  studio: {
    id: 'studio', name: 'Studio', version: '1.0.0',
    description: 'Content creator dashboard and analytics.',
    shortDescription: 'Creator dashboard.',
    category: 'finance', icon: 'videocam-outline', route: '/(os)/studio',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: true,
    color: '#FF2D55', rating: 4.3, reviewCount: 800, downloadCount: 25000,
    sizeMB: 30, permissions: ['media', 'notifications'],
    tags: ['creator', 'video', 'analytics'],
  },
  pulse: {
    id: 'pulse', name: 'Pulse', version: '1.0.0',
    description: 'Financial analytics and market insights.',
    shortDescription: 'Financial analytics.',
    category: 'finance', icon: 'pulse-outline', route: '/(finance)/pulse',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: true,
    color: '#FF3B30', rating: 4.2, reviewCount: 500, downloadCount: 15000,
    sizeMB: 12, permissions: ['wallet_read'],
    tags: ['analytics', 'finance', 'insights'],
  },

  // ─── COMMERCE ───
  shop: {
    id: 'shop', name: 'Shop', version: '1.0.0',
    description: 'Buy and sell products in the MTAA marketplace.',
    shortDescription: 'E-commerce marketplace.',
    category: 'commerce', icon: 'cart-outline', route: '/(commerce)/shop',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: true,
    color: '#FF9500', rating: 4.4, reviewCount: 1500, downloadCount: 40000,
    sizeMB: 15, permissions: ['wallet_read', 'wallet_write'],
    tags: ['shopping', 'ecommerce', 'buy', 'sell'],
  },
  marketplace: {
    id: 'marketplace', name: 'Marketplace', version: '1.0.0',
    description: 'Local marketplace for goods and services.',
    shortDescription: 'Local buy and sell.',
    category: 'commerce', icon: 'basket-outline', route: '/(commerce)/marketplace',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: true,
    color: '#FF9500', rating: 4.3, reviewCount: 1200, downloadCount: 35000,
    sizeMB: 15, permissions: ['wallet_read', 'wallet_write', 'location'],
    tags: ['marketplace', 'local', 'buy', 'sell'],
  },
  jobs: {
    id: 'jobs', name: 'Jobs', version: '1.0.0',
    description: 'Find jobs and hire talent.',
    shortDescription: 'Job marketplace.',
    category: 'commerce', icon: 'briefcase-outline', route: '/(commerce)/jobs',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: true,
    color: '#5856D6', rating: 4.1, reviewCount: 900, downloadCount: 20000,
    sizeMB: 12, permissions: ['identity', 'notifications'],
    tags: ['jobs', 'hiring', 'career'],
  },
  restaurant: {
    id: 'restaurant', name: 'Restaurant', version: '1.0.0',
    description: 'Restaurant management and food ordering.',
    shortDescription: 'Restaurant & food.',
    category: 'commerce', icon: 'restaurant-outline', route: '/(commerce)/restaurant',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: true,
    color: '#FF2D55', rating: 4.3, reviewCount: 700, downloadCount: 18000,
    sizeMB: 18, permissions: ['wallet_read', 'wallet_write', 'location'],
    tags: ['food', 'restaurant', 'order'],
  },

  // ─── TRANSPORT ───
  mtaxi: {
    id: 'mtaxi', name: 'MTaxi', version: '2.0.0',
    description: 'Book rides and drive with MTaxi.',
    shortDescription: 'Ride hailing.',
    category: 'transport', icon: 'car-outline', route: '/(transport)/mtaxi',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: true,
    color: '#007AFF', rating: 4.5, reviewCount: 2500, downloadCount: 60000,
    sizeMB: 20, permissions: ['location', 'wallet_read', 'wallet_write'],
    tags: ['taxi', 'ride', 'transport'],
  },
  mtruck: {
    id: 'mtruck', name: 'MTruck', version: '1.0.0',
    description: 'Truck logistics and freight management.',
    shortDescription: 'Truck logistics.',
    category: 'transport', icon: 'truck-outline', route: '/(transport)/mtruck',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: true,
    color: '#34C759', rating: 4.2, reviewCount: 600, downloadCount: 12000,
    sizeMB: 18, permissions: ['location', 'wallet_read'],
    tags: ['truck', 'logistics', 'freight'],
  },
  boda: {
    id: 'boda', name: 'Boda', version: '1.0.0',
    description: 'Motorcycle taxi booking.',
    shortDescription: 'Boda boda rides.',
    category: 'transport', icon: 'bicycle-outline', route: '/(transport)/boda',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: true,
    color: '#FF9500', rating: 4.1, reviewCount: 800, downloadCount: 15000,
    sizeMB: 15, permissions: ['location', 'wallet_read'],
    tags: ['boda', 'motorcycle', 'ride'],
  },
  garage: {
    id: 'garage', name: 'Garage', version: '1.0.0',
    description: 'Vehicle maintenance and garage services.',
    shortDescription: 'Vehicle services.',
    category: 'transport', icon: 'construct-outline', route: '/(transport)/garage',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: true,
    color: '#8E8E93', rating: 4.0, reviewCount: 500, downloadCount: 10000,
    sizeMB: 12, permissions: ['location'],
    tags: ['garage', 'vehicle', 'repair'],
  },

  // ─── SOCIAL ───
  streets: {
    id: 'streets', name: 'Streets', version: '2.0.0',
    description: 'Share moments, photos, and videos with your community.',
    shortDescription: 'Social sharing.',
    category: 'social', icon: 'globe-outline', route: '/(os)/streets',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: true,
    color: '#007AFF', rating: 4.6, reviewCount: 3000, downloadCount: 70000,
    sizeMB: 25, permissions: ['media', 'location', 'notifications'],
    tags: ['social', 'feed', 'photos', 'videos'],
  },
  tribes: {
    id: 'tribes', name: 'Tribes', version: '1.0.0',
    description: 'Join communities and connect with like-minded people.',
    shortDescription: 'Community groups.',
    category: 'social', icon: 'people-outline', route: '/(os)/tribes',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: true,
    color: '#AF52DE', rating: 4.4, reviewCount: 1500, downloadCount: 35000,
    sizeMB: 18, permissions: ['notifications', 'media'],
    tags: ['community', 'groups', 'social'],
  },
  mstudio: {
    id: 'mstudio', name: 'MStudio', version: '1.0.0',
    description: 'Create and share video content.',
    shortDescription: 'Video creation.',
    category: 'social', icon: 'film-outline', route: '/(os)/studio',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: true,
    color: '#FF2D55', rating: 4.5, reviewCount: 2000, downloadCount: 45000,
    sizeMB: 35, permissions: ['media', 'camera', 'notifications'],
    tags: ['video', 'creator', 'studio'],
  },

  // ─── EDUCATION ───
  education: {
    id: 'education', name: 'Education', version: '1.0.0',
    description: 'School management, assignments, and learning.',
    shortDescription: 'Education platform.',
    category: 'education', icon: 'school-outline', route: '/(education)',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: true,
    color: '#5856D6', rating: 4.3, reviewCount: 1000, downloadCount: 25000,
    sizeMB: 22, permissions: ['identity', 'notifications'],
    tags: ['education', 'school', 'learning'],
  },

  // ─── TOOLS ───
  calculator: {
    id: 'calculator', name: 'Calculator', version: '1.0.0',
    description: 'Basic calculator app.',
    shortDescription: 'Calculator.',
    category: 'tools', icon: 'calculator-outline', route: '/(os)/calculator',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: false,
    color: '#8E8E93', rating: 4.0, reviewCount: 300, downloadCount: 5000,
    sizeMB: 2, permissions: [],
    tags: ['calculator', 'math'],
  },
  documents: {
    id: 'documents', name: 'Documents', version: '1.0.0',
    description: 'File manager and document viewer.',
    shortDescription: 'File manager.',
    category: 'tools', icon: 'document-outline', route: '/(os)/documents',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: false,
    color: '#007AFF', rating: 4.2, reviewCount: 600, downloadCount: 12000,
    sizeMB: 8, permissions: ['media'],
    tags: ['files', 'documents', 'manager'],
  },
  gallery: {
    id: 'gallery', name: 'Gallery', version: '1.0.0',
    description: 'Photo and video gallery.',
    shortDescription: 'Media gallery.',
    category: 'tools', icon: 'images-outline', route: '/(os)/gallery',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: false,
    color: '#FF2D55', rating: 4.1, reviewCount: 500, downloadCount: 10000,
    sizeMB: 10, permissions: ['media'],
    tags: ['photos', 'gallery', 'media'],
  },
  messages: {
    id: 'messages', name: 'Messages', version: '1.0.0',
    description: 'SMS and messaging.',
    shortDescription: 'Messaging.',
    category: 'tools', icon: 'chatbubble-outline', route: '/(os)/messages',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: true,
    color: '#34C759', rating: 4.3, reviewCount: 800, downloadCount: 15000,
    sizeMB: 12, permissions: ['notifications'],
    tags: ['messages', 'sms', 'chat'],
  },
  clock: {
    id: 'clock', name: 'Clock', version: '1.0.0',
    description: 'Alarm clock and timer.',
    shortDescription: 'Clock & alarms.',
    category: 'tools', icon: 'time-outline', route: '/(os)/clock',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: false,
    color: '#8E8E93', rating: 3.9, reviewCount: 200, downloadCount: 3000,
    sizeMB: 3, permissions: [],
    tags: ['clock', 'alarm', 'timer'],
  },
  scheduler: {
    id: 'scheduler', name: 'Scheduler', version: '1.0.0',
    description: 'Calendar and event scheduling.',
    shortDescription: 'Calendar & events.',
    category: 'tools', icon: 'calendar-outline', route: '/(os)/scheduler',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: true,
    color: '#007AFF', rating: 4.0, reviewCount: 400, downloadCount: 8000,
    sizeMB: 8, permissions: ['notifications'],
    tags: ['calendar', 'schedule', 'events'],
  },
  sim: {
    id: 'sim', name: 'SIM', version: '1.0.0',
    description: 'SIM card management.',
    shortDescription: 'SIM management.',
    category: 'tools', icon: 'sim-outline', route: '/(os)/sim',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: false,
    color: '#8E8E93', rating: 3.8, reviewCount: 150, downloadCount: 2000,
    sizeMB: 4, permissions: [],
    tags: ['sim', 'mobile', 'network'],
  },
  recents: {
    id: 'recents', name: 'Recents', version: '1.0.0',
    description: 'Recent calls and activity.',
    shortDescription: 'Recent activity.',
    category: 'tools', icon: 'call-outline', route: '/(os)/recents',
    developer: 'MTAA OS', isOSApp: true, requiresAuth: false,
    color: '#8E8E93', rating: 3.9, reviewCount: 200, downloadCount: 3000,
    sizeMB: 4, permissions: [],
    tags: ['calls', 'recents', 'activity'],
  },
};

export type AppRegistry = typeof appRegistry;
export type AppId = keyof AppRegistry;

export const getAppById = (id: AppId) => appRegistry[id];
export const getAppsByCategory = (category: string) =>
  Object.values(appRegistry).filter((app: any) => app.category === category);
export const getAllApps = () => Object.values(appRegistry);
export const getCategories = () =>
  [...new Set(Object.values(appRegistry).map((app: any) => app.category))];
