import { AppManifest } from '../types';

export const simManifest: AppManifest = {
  id: 'sim',
  name: 'SIM Tools',
  description: 'SIM card management, USSD codes, and airtime',
  version: '1.0.0',
  category: 'utility',
  icon: 'smartphone',
  color: '#06B6D4',
  author: 'MTAA OS',
  size: '3MB',
  rating: 4.2,
  installs: 0,
  isOSBased: false,
  entryPoint: '/(os)/sim',
  permissions: ['phone', 'sms'],
  screens: [
    { route: '/(os)/sim', label: 'SIM', icon: 'smartphone' },
    { route: '/(os)/sim/ussd', label: 'USSD', icon: 'hash' },
    { route: '/(os)/sim/airtime', label: 'Airtime', icon: 'credit-card' },
    { route: '/(os)/sim/data', label: 'Data', icon: 'wifi' },
  ],
  features: [
    'SIM card info and status',
    'USSD code runner',
    'Airtime balance check and top-up',
    'Data bundle management',
    'Multi-SIM support',
  ],
  minOSVersion: '1.0.0',
  supportedPlatforms: ['android'],
  requiresAuth: false,
  hasInAppPurchases: false,
  dataUsage: 'none',
  offlineSupport: true,
};
