import React,{useState}from'react';import{View,Text,TouchableOpacity,ActivityIndicator,RefreshControl,ScrollView,Modal,TextInput}from'react-native';import{useInstitutions}from'../hooks/useIdentity';import{Ionicons}from'@expo/vector-icons';
function IM({v,o}:{v:boolean;o:()=>void}){const{create}=useInstitutions();const[n,setN]=useState('');const[t,setT]=useState('school');const[addr,setA]=useState('');const[phone,setP]=useState('');const[email,setE]=useState('');const[sv,setS]=useState(false);const types=['school','college','university','vocational','other'];
const save=async()=>{if(!n||!addr)return;setS(true);try{await create({name:n,institution_type:t,address:addr,phone:phone||null,email:email||null,status:'active'});o();}catch(e){}finally{setS(false);}};
return(<Modal visible={v}animationType="slide"transparent onRequestClose={o}><View style={{flex:1,backgroundColor:'rgba(0,0,0,0.5)',justifyContent:'flex-end'}}><View style={{backgroundColor:'#fff',borderTopLeftRadius:20,borderTopRightRadius:20,padding:20}}><Text style={{fontSize:18,fontWeight:'700',marginBottom:14}}>New Institution</Text><TextInput placeholder="Name"value={n}onChangeText={setN}style={{backgroundColor:'#F3F4F6',borderRadius:12,padding:12,marginBottom:10,fontSize:14}}/><View style={{flexDirection:'row',flexWrap:'wrap',marginBottom:10}}>{types.map(t2=><TouchableOpacity key={t2}onPress={()=>setT(t2)}style={{backgroundColor:t===t2?'#3B82F6':'#F3F4F6',paddingHorizontal:12,paddingVertical:6,borderRadius:16,marginRight:8,marginBottom:8}}><Text style={{fontSize:12,fontWeight:'600',color:t===t2?'#fff':'#374151',textTransform:'capitalize'}}>{t2}</Text></TouchableOpacity>)}</View><TextInput placeholder="Address"value={addr}onChangeText={setA}style={{backgroundColor:'#F3F4F6',borderRadius:12,padding:12,marginBottom:10,fontSize:14}}/><TextInput placeholder="Phone"keyboardType="phone-pad"value={phone}onChangeText={setP}style={{backgroundColor:'#F3F4F6',borderRadius:12,padding:12,marginBottom:10,fontSize:14}}/><TextInput placeholder="Email"keyboardType="email-address"value={email}onChangeText={setE}style={{backgroundColor:'#F3F4F6',borderRadius:12,padding:12,marginBottom:16,fontSize:14}}/><TouchableOpacity onPress={save}disabled={sv}style={{backgroundColor:sv?'#D1D5DB':'#3B82F6',borderRadius:14,padding:14,alignItems:'center'}}><Text style={{color:'#fff',fontWeight:'700',fontSize:15}}>{sv?'Creating...':'Create'}</Text></TouchableOpacity></View></View></Modal>);}
export default function InstitutionListScreen(){const[im,setIm]=useState(false);const[rf,setRf]=useState(false);const{institutions,loading,error,refresh,create}=useInstitutions();
const ra=async()=>{setRf(true);await refresh();setRf(false);};
if(loading&&!institutions.length)return<View style={{flex:1,justifyContent:'center',alignItems:'center'}}><ActivityIndicator size="large"color="#3B82F6"/></View>;
if(error&&!institutions.length)return<View style={{flex:1,justifyContent:'center',alignItems:'center',padding:20}}><Ionicons name="warning"size={40}color="#EF4444"/><Text style={{marginTop:12,color:'#EF4444'}}>{error}</Text><TouchableOpacity onPress={ra}style={{marginTop:16,backgroundColor:'#3B82F6',paddingHorizontal:20,paddingVertical:10,borderRadius:20}}><Text style={{color:'#fff',fontWeight:'600'}}>Retry</Text></TouchableOpacity></View>;
return(<View style={{flex:1,backgroundColor:'#F9FAFB'}}><View style={{backgroundColor:'#fff',paddingHorizontal:16,paddingTop:50,paddingBottom:12}}><Text style={{fontSize:20,fontWeight:'800',color:'#111827'}}>Institutions</Text><Text style={{fontSize:13,color:'#6B7280',marginTop:2}}>Manage schools & colleges</Text></View><TouchableOpacity onPress={()=>setIm(true)}style={{backgroundColor:'#3B82F6',borderRadius:14,padding:14,alignItems:'center',margin:12}}><Text style={{color:'#fff',fontWeight:'700',fontSize:15}}>+ Add Institution</Text></TouchableOpacity><ScrollView refreshControl={<RefreshControl refreshing={rf}onRefresh={ra}/>}contentContainerStyle={{padding:12}}>{institutions.map(i=><View key={i.id}style={{backgroundColor:'#fff',borderRadius:12,padding:14,marginBottom:8}}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><Text style={{fontWeight:'700',fontSize:15}}>{i.name}</Text><View style={{backgroundColor:i.status==='active'?'#D1FAE5':'#FEE2E2',paddingHorizontal:8,paddingVertical:3,borderRadius:10}}><Text style={{fontSize:11,fontWeight:'600',color:i.status==='active'?'#059669':'#DC2626'}}>{i.status}</Text></View></View><Text style={{fontSize:12,color:'#6B7280',marginTop:4}}>{i.institution_type} · {i.address}</Text><Text style={{fontSize:11,color:'#9CA3AF',marginTop:2}}>{i.phone||'No phone'} · {i.email||'No email'}</Text></View>)}{institutions.length===0&&!loading&&<Text style={{textAlign:'center',color:'#9CA3AF',marginVertical:20}}>No institutions yet</Text>}</ScrollView><IM v={im}o={()=>setIm(false)}/></View>);}
