import { AppManifest } from '../types';

export const clockManifest: AppManifest = {
  id: 'clock',
  name: 'Clock',
  description: 'World clock, alarms, timers, and stopwatch',
  version: '1.0.0',
  category: 'utility',
  icon: 'clock',
  color: '#F59E0B',
  author: 'MTAA OS',
  size: '2MB',
  rating: 4.3,
  installs: 0,
  isOSBased: false,
  entryPoint: '/(os)/clock',
  permissions: ['notifications'],
  screens: [
    { route: '/(os)/clock', label: 'Clock', icon: 'clock' },
    { route: '/(os)/clock/alarms', label: 'Alarms', icon: 'bell' },
    { route: '/(os)/clock/timer', label: 'Timer', icon: 'hourglass' },
    { route: '/(os)/clock/stopwatch', label: 'Stopwatch', icon: 'watch' },
    { route: '/(os)/clock/world', label: 'World', icon: 'globe' },
  ],
  features: [
    'Current time with timezone support',
    'Set and manage alarms',
    'Countdown timers',
    'Stopwatch with lap recording',
    'World clock for multiple cities',
  ],
  minOSVersion: '1.0.0',
  supportedPlatforms: ['ios', 'android', 'web'],
  requiresAuth: false,
  hasInAppPurchases: false,
  dataUsage: 'none',
  offlineSupport: true,
};
