import { supabase } from '@/lib/supabase';import type{Database}from'@/lib/supabase';
type Cls=Database['public']['Tables']['education_classes']['Row'];type Sub=Database['public']['Tables']['education_subjects']['Row'];type Les=Database['public']['Tables']['education_lessons']['Row'];type Asn=Database['public']['Tables']['education_assignments']['Row'];type Subm=Database['public']['Tables']['education_submissions']['Row'];type Grd=Database['public']['Tables']['education_grades']['Row'];
export async function getClasses(instId:string){const{d,e}=await supabase.from('education_classes').select('*,teacher:education_teachers(user:user_profiles(full_name)),subject:education_subjects(name)').eq('institution_id',instId).order('name');if(e)throw e;return d||[];}
export async function getClass(id:string){const{d,e}=await supabase.from('education_classes').select('*,teacher:education_teachers(user:user_profiles(full_name)),students:education_students(id,full_name)').eq('id',id).single();if(e)throw e;return d;}
export async function createClass(c:Omit<Cls,'id'|'created_at'|'updated_at'>){const{d,e}=await supabase.from('education_classes').insert(c).select().single();if(e)throw e;return d;}
export async function updateClass(id:string,u:Partial<Cls>){const{d,e}=await supabase.from('education_classes').update(u).eq('id',id).select().single();if(e)throw e;return d;}
export async function getSubjects(instId?:string){let q=supabase.from('education_subjects').select('*').order('name');if(instId)q=q.eq('institution_id',instId);const{d,e}=await q;if(e)throw e;return d||[];}
export async function createSubject(s:Omit<Sub,'id'|'created_at'>){const{d,e}=await supabase.from('education_subjects').insert(s).select().single();if(e)throw e;return d;}
export async function getLessons(classId:string){const{d,e}=await supabase.from('education_lessons').select('*,subject:education_subjects(name)').eq('class_id',classId).order('lesson_date',{ascending:false});if(e)throw e;return d||[];}
export async function createLesson(l:Omit<Les,'id'|'created_at'|'updated_at'>){const{d,e}=await supabase.from('education_lessons').insert(l).select().single();if(e)throw e;return d;}
export async function getAssignments(classId:string){const{d,e}=await supabase.from('education_assignments').select('*,subject:education_subjects(name)').eq('class_id',classId).order('due_date');if(e)throw e;return d||[];}
export async function createAssignment(a:Omit<Asn,'id'|'created_at'|'updated_at'>){const{d,e}=await supabase.from('education_assignments').insert(a).select().single();if(e)throw e;return d;}
export async function getSubmissions(assignmentId:string){const{d,e}=await supabase.from('education_submissions').select('*,student:education_students(full_name)').eq('assignment_id',assignmentId).order('submitted_at',{ascending:false});if(e)throw e;return d||[];}
export async function submitWork(s:Omit<Subm,'id'|'submitted_at'|'graded_at'>){const{d,e}=await supabase.from('education_submissions').insert({...s,status:'submitted'}).select().single();if(e)throw e;return d;}
export async function gradeSubmission(id:string,score:number,feedback?:string,gradedBy?:string){const{d,e}=await supabase.from('education_submissions').update({score,feedback,graded_by:gradedBy,graded_at:new Date().toISOString(),status:'graded'}).eq('id',id).select().single();if(e)throw e;return d;}
export async function getGrades(studentId:string){const{d,e}=await supabase.from('education_grades').select('*,subject:education_subjects(name),assignment:education_assignments(title)').eq('student_id',studentId).order('created_at',{ascending:false});if(e)throw e;return d||[];}
export async function createGrade(g:Omit<Grd,'id'|'created_at'>){const{d,e}=await supabase.from('education_grades').insert(g).select().single();if(e)throw e;return d;}
export async function getTeacherDashboard(teacherId:string){const[{data:cls},{data:asn},{data:sub}] = await Promise.all([supabase.from('education_classes').select('id,name,student_count').eq('teacher_id',teacherId),supabase.from('education_assignments').select('id,title,due_date,class_id').eq('teacher_id',teacherId).order('due_date').limit(5),supabase.from('education_submissions').select('id,status,submitted_at,student:education_students(full_name),assignment:education_assignments(title)').in('assignment_id',supabase.from('education_assignments').select('id').eq('teacher_id',teacherId)).eq('status','submitted').order('submitted_at').limit(5)]);return{classes:cls||[],assignments:asn||[],pendingSubmissions:sub||[]};
}
