import{supabase}from'@/lib/supabase';import type{Database}from'@/lib/supabase';
type EF=Database['public']['Tables']['education_feeds']['Row'];type FC=Database['public']['Tables']['education_feed_comments']['Row'];type FL=Database['public']['Tables']['education_feed_likes']['Row'];type SFA=Database['public']['Tables']['student_finance_accounts']['Row'];type FS=Database['public']['Tables']['fee_structures']['Row'];type FT=Database['public']['Tables']['fee_transactions']['Row'];type BA=Database['public']['Tables']['bursary_applications']['Row'];
export async function getFeedPosts(instId:string,opts?:{type?:string;limit?:number}){let q=supabase.from('education_feeds').select('*,author:user_profiles(full_name,avatar_url),likes:education_feed_likes(count),comments:education_feed_comments(count)').eq('institution_id',instId).order('created_at',{ascending:false});if(opts?.type)q=q.eq('post_type',opts.type);if(opts?.limit)q=q.limit(opts.limit);const{d,e}=await q;if(e)throw e;return d||[];}
export async function createFeedPost(p:Omit<EF,'id'|'created_at'|'updated_at'>){const{d,e}=await supabase.from('education_feeds').insert(p).select().single();if(e)throw e;return d;}
export async function deleteFeedPost(id:string){const{e}=await supabase.from('education_feeds').delete().eq('id',id);if(e)throw e;}
export async function pinFeedPost(id:string,pin:boolean){const{d,e}=await supabase.from('education_feeds').update({is_pinned:pin,pinned_at:pin?new Date().toISOString():null}).eq('id',id).select().single();if(e)throw e;return d;}
export async function getComments(postId:string){const{d,e}=await supabase.from('education_feed_comments').select('*,author:user_profiles(full_name,avatar_url)').eq('post_id',postId).order('created_at',{ascending:true});if(e)throw e;return d||[];}
export async function addComment(c:Omit<FC,'id'|'created_at'>){const{d,e}=await supabase.from('education_feed_comments').insert(c).select().single();if(e)throw e;return d;}
export async function toggleLike(postId:string,userId:string){const{d:existing}=await supabase.from('education_feed_likes').select('id').eq('post_id',postId).eq('user_id',userId).single();if(existing){const{e}=await supabase.from('education_feed_likes').delete().eq('id',existing.id);if(e)throw e;return{liked:false};}else{const{d,e}=await supabase.from('education_feed_likes').insert({post_id:postId,user_id:userId}).select().single();if(e)throw e;return{liked:true,data:d};}}
export async function getStudentFinance(studentId:string){const{d,e}=await supabase.from('student_finance_accounts').select('*,student:education_students(full_name)').eq('student_id',studentId).single();if(e&&e.code!=='PGRST116')throw e;return d||null;}
export async function getFeeStructures(instId:string){const{d,e}=await supabase.from('fee_structures').select('*').eq('institution_id',instId).order('due_date');if(e)throw e;return d||[];}
export async function getFeeTransactions(studentId:string){const{d,e}=await supabase.from('fee_transactions').select('*,fee:fee_structures(name)').eq('student_id',studentId).order('created_at',{ascending:false});if(e)throw e;return d||[];}
export async function makePayment(t:Omit<FT,'id'|'created_at'>){const{d,e}=await supabase.from('fee_transactions').insert(t).select().single();if(e)throw e;return d;}
export async function getSavingsGoal(studentId:string){const{d,e}=await supabase.from('student_finance_accounts').select('savings_goal,savings_balance').eq('student_id',studentId).single();if(e&&e.code!=='PGRST116')throw e;return d||{savings_goal:0,savings_balance:0};}
export async function updateSavingsGoal(studentId:string,goal:number){const{d,e}=await supabase.from('student_finance_accounts').update({savings_goal:goal}).eq('student_id',studentId).select().single();if(e)throw e;return d;}
export async function depositSavings(studentId:string,amount:number){const{d,e}=await supabase.from('student_finance_accounts').update({savings_balance:supabase.rpc('increment_savings',{sid:studentId,amt:amount})}).eq('student_id',studentId).select().single();if(e)throw e;return d;}
export async function getBursaryApplications(studentId?:string,instId?:string){let q=supabase.from('bursary_applications').select('*,student:education_students(full_name)').order('created_at',{ascending:false});if(studentId)q=q.eq('student_id',studentId);if(instId)q=q.eq('institution_id',instId);const{d,e}=await q;if(e)throw e;return d||[];}
export async function applyBursary(b:Omit<BA,'id'|'created_at'|'updated_at'>){const{d,e}=await supabase.from('bursary_applications').insert(b).select().single();if(e)throw e;return d;}
export async function reviewBursary(id:string,status:'approved'|'rejected',amount?:number,notes?:string){const{d,e}=await supabase.from('bursary_applications').update({status,approved_amount:amount,review_notes:notes,reviewed_at:new Date().toISOString()}).eq('id',id).select().single();if(e)throw e;return d;}
export async function createFeeStructure(f:Omit<FS,'id'|'created_at'|'updated_at'>){const{d,e}=await supabase.from('fee_structures').insert(f).select().single();if(e)throw e;return d;}
export async function chargeFee(studentId:string,feeId:string,amount:number){const{d,e}=await supabase.from('fee_transactions').insert({student_id:studentId,fee_id:feeId,amount,transaction_type:'fee',status:'pending'}).select().single();if(e)throw e;return d;}
export async function getFinanceDashboard(instId:string){const[{data:stu},{data:bal},{data:due},{data:bur}]=await Promise.all([supabase.from('education_students').select('id').eq('institution_id',instId),supabase.from('student_finance_accounts').select('balance').eq('institution_id',instId),supabase.from('fee_transactions').select('amount').eq('institution_id',instId).eq('status','pending'),supabase.from('bursary_applications').select('requested_amount').eq('institution_id',instId).eq('status','pending')]);return{totalStudents:stu?.length||0,totalBalance:(bal||[]).reduce((s,b)=>s+(b.balance||0),0),totalDue:(due||[]).reduce((s,d)=>s+(d.amount||0),0),pendingBursaries:(bur||[]).reduce((s,b)=>s+(b.requested_amount||0),0)};}
