import{supabase}from'@/lib/supabase';import type{Database}from'@/lib/supabase';
type Inst=Database['public']['Tables']['education_institutions']['Row'];type Tch=Database['public']['Tables']['education_teachers']['Row'];type Stu=Database['public']['Tables']['education_students']['Row'];type QR=Database['public']['Tables']['education_qr_sessions']['Row'];
export async function getInstitutions(){const{d,e}=await supabase.from('education_institutions').select('*').order('name');if(e)throw e;return d||[];}
export async function getInstitution(id:string){const{d,e}=await supabase.from('education_institutions').select('*').eq('id',id).single();if(e)throw e;return d;}
export async function createInstitution(i:Omit<Inst,'id'|'created_at'|'updated_at'>){const{d,e}=await supabase.from('education_institutions').insert(i).select().single();if(e)throw e;return d;}
export async function updateInstitution(id:string,u:Partial<Inst>){const{d,e}=await supabase.from('education_institutions').update(u).eq('id',id).select().single();if(e)throw e;return d;}
export async function getTeachers(instId?:string){let q=supabase.from('education_teachers').select('*,user:user_profiles(full_name,email,phone)').order('created_at',{ascending:false});if(instId)q=q.eq('institution_id',instId);const{d,e}=await q;if(e)throw e;return d||[];}
export async function getTeacher(id:string){const{d,e}=await supabase.from('education_teachers').select('*,user:user_profiles(full_name,email,phone)').eq('id',id).single();if(e)throw e;return d;}
export async function createTeacher(t:Omit<Tch,'id'|'created_at'|'updated_at'>){const{d,e}=await supabase.from('education_teachers').insert(t).select().single();if(e)throw e;return d;}
export async function updateTeacher(id:string,u:Partial<Tch>){const{d,e}=await supabase.from('education_teachers').update(u).eq('id',id).select().single();if(e)throw e;return d;}
export async function getStudents(instId?:string,classId?:string){let q=supabase.from('education_students').select('*,user:user_profiles(full_name,email,phone),class:education_classes(name)').order('created_at',{ascending:false});if(instId)q=q.eq('institution_id',instId);if(classId)q=q.eq('class_id',classId);const{d,e}=await q;if(e)throw e;return d||[];}
export async function getStudent(id:string){const{d,e}=await supabase.from('education_students').select('*,user:user_profiles(full_name,email,phone),class:education_classes(name)').eq('id',id).single();if(e)throw e;return d;}
export async function createStudent(s:Omit<Stu,'id'|'created_at'|'updated_at'>){const{d,e}=await supabase.from('education_students').insert(s).select().single();if(e)throw e;return d;}
export async function updateStudent(id:string,u:Partial<Stu>){const{d,e}=await supabase.from('education_students').update(u).eq('id',id).select().single();if(e)throw e;return d;}
export async function createQRSession(q:Omit<QR,'id'|'created_at'>){const{d,e}=await supabase.from('education_qr_sessions').insert(q).select().single();if(e)throw e;return d;}
export async function getActiveQRSession(instId:string){const{d,e}=await supabase.from('education_qr_sessions').select('*').eq('institution_id',instId).eq('is_active',true).order('created_at',{ascending:false}).limit(1).single();if(e&&e.code!=='PGRST116')throw e;return d||null;}
export async function verifyQRSession(sessionId:string){const{d,e}=await supabase.from('education_qr_sessions').update({scan_count:supabase.rpc('increment',{x:1}),last_scanned_at:new Date().toISOString()}).eq('id',sessionId).select().single();if(e)throw e;return d;}
