// @ts-nocheck
import{supabase}from'@/lib/supabase';import type{Database}from'@/lib/supabase';
type TS=Database['public']['Tables']['education_teacher_services']['Row'];type TB=Database['public']['Tables']['education_teacher_bookings']['Row'];type CL=Database['public']['Tables']['education_content_library']['Row'];type LS=Database['public']['Tables']['education_live_streams']['Row'];
export async function getTeacherServices(teacherId?:string){let q=supabase.from('education_teacher_services').select('*,teacher:education_teachers(user:user_profiles(full_name))').order('created_at',{ascending:false});if(teacherId)q=q.eq('teacher_id',teacherId);const{d,e}=await q;if(e)throw e;return d||[];}
export async function createService(s:Omit<TS,'id'|'created_at'|'updated_at'>){const{d,e}=await supabase.from('education_teacher_services').insert(s).select().single();if(e)throw e;return d;}
export async function updateService(id:string,u:Partial<TS>){const{d,e}=await supabase.from('education_teacher_services').update(u).eq('id',id).select().single();if(e)throw e;return d;}
export async function getBookings(studentId?:string,teacherId?:string){let q=supabase.from('education_teacher_bookings').select('*,service:education_teacher_services(title),student:education_students(full_name),teacher:education_teachers(user:user_profiles(full_name))').order('booking_date',{ascending:true});if(studentId)q=q.eq('student_id',studentId);if(teacherId)q=q.eq('teacher_id',teacherId);const{d,e}=await q;if(e)throw e;return d||[];}
export async function createBooking(b:Omit<TB,'id'|'created_at'|'updated_at'>){const{d,e}=await supabase.from('education_teacher_bookings').insert(b).select().single();if(e)throw e;return d;}
export async function updateBooking(id:string,u:Partial<TB>){const{d,e}=await supabase.from('education_teacher_bookings').update(u).eq('id',id).select().single();if(e)throw e;return d;}
export async function getContentLibrary(instId?:string,subjectId?:string){let q=supabase.from('education_content_library').select('*,subject:education_subjects(name),uploader:education_teachers(user:user_profiles(full_name))').order('created_at',{ascending:false});if(instId)q=q.eq('institution_id',instId);if(subjectId)q=q.eq('subject_id',subjectId);const{d,e}=await q;if(e)throw e;return d||[];}
export async function uploadContent(c:Omit<CL,'id'|'created_at'>){const{d,e}=await supabase.from('education_content_library').insert(c).select().single();if(e)throw e;return d;}
export async function getLiveStreams(instId?:string,status?:string){let q=supabase.from('education_live_streams').select('*,host:education_teachers(user:user_profiles(full_name))').order('scheduled_at',{ascending:true});if(instId)q=q.eq('institution_id',instId);if(status)q=q.eq('status',status);const{d,e}=await q;if(e)throw e;return d||[];}
export async function createStream(s:Omit<LS,'id'|'created_at'|'updated_at'>){const{d,e}=await supabase.from('education_live_streams').insert(s).select().single();if(e)throw e;return d;}
export async function updateStream(id:string,u:Partial<LS>){const{d,e}=await supabase.from('education_live_streams').update(u).eq('id',id).select().single();if(e)throw e;return d;}
export async function getTeacherEarnings(teacherId:string){const[{data:svcs},{data:bks}]=await Promise.all([supabase.from('education_teacher_services').select('id,price').eq('teacher_id',teacherId),supabase.from('education_teacher_bookings').select('service_id,status').eq('teacher_id',teacherId).eq('status','completed')]);const svcMap=new Map((svcs||[]).map((s: any) =>[s.id,s.price]));const total=(bks||[]).reduce((sum,b)=>sum+(svcMap.get(b.service_id)||0),0);return{total,bookings:bks?.length||0,services:svcs?.length||0};}
