import{supabase}from'@/lib/supabase';import type{Database}from'@/lib/supabase';
type RT=Database['public']['Tables']['education_transport_routes']['Row'];type ST=Database['public']['Tables']['education_student_transport']['Row'];
export async function getRoutes(instId:string){const{d,e}=await supabase.from('education_transport_routes').select('*').eq('institution_id',instId).order('route_name');if(e)throw e;return d||[];}
export async function getRoute(id:string){const{d,e}=await supabase.from('education_transport_routes').select('*,students:education_student_transport(student:education_students(full_name))').eq('id',id).single();if(e)throw e;return d;}
export async function createRoute(r:Omit<RT,'id'|'created_at'|'updated_at'>){const{d,e}=await supabase.from('education_transport_routes').insert(r).select().single();if(e)throw e;return d;}
export async function updateRoute(id:string,u:Partial<RT>){const{d,e}=await supabase.from('education_transport_routes').update(u).eq('id',id).select().single();if(e)throw e;return d;}
export async function assignStudentTransport(s:Omit<ST,'id'|'created_at'|'updated_at'>){const{d,e}=await supabase.from('education_student_transport').insert(s).select().single();if(e)throw e;return d;}
export async function getStudentTransport(studentId:string){const{d,e}=await supabase.from('education_student_transport').select('*,route:education_transport_routes(route_name,vehicle_plate,driver_name)').eq('student_id',studentId).order('created_at',{ascending:false});if(e)throw e;return d||[];}
export async function recordCustodyScan(transportId:string,scanType:'pickup'|'dropoff',scannedBy:string,method:'qr'|'fingerprint',lat?:number,lng?:number){const{d,e}=await supabase.from('education_student_transport').update({last_scan_type:scanType,last_scanned_by:scannedBy,last_scan_method:method,last_scan_lat:lat,last_scan_lng:lng,last_scan_at:new Date().toISOString()}).eq('id',transportId).select().single();if(e)throw e;return d;}
export async function getTransportAnomalies(instId:string){const{d,e}=await supabase.from('education_student_transport').select('*,student:education_students(full_name),route:education_transport_routes(route_name)').eq('anomaly_flag',true).eq('institution_id',instId).order('anomaly_detected_at',{ascending:false});if(e)throw e;return d||[];}
