import{supabase}from'@/lib/supabase';import type{Database}from'@/types/supabase';
type GF=Database['public']['Tables']['child_geofences']['Row'];type SOS=Database['public']['Tables']['child_sos_logs']['Row'];type EC=Database['public']['Tables']['child_emergency_contacts']['Row'];type INC=Database['public']['Tables']['child_safety_incidents']['Row'];
export async function getGeofences(instId:string,childId?:string){let q=supabase.from('child_geofences').select('*').eq('institution_id',instId).eq('is_active',true);if(childId)q=q.eq('child_id',childId);const{d,e}=await q;if(e)throw e;return d||[];}
export async function createGeofence(g:Omit<GF,'id'|'created_at'|'updated_at'>){const{d,e}=await supabase.from('child_geofences').insert(g).select().single();if(e)throw e;return d;}
export async function updateGeofence(id:string,u:Partial<GF>){const{d,e}=await supabase.from('child_geofences').update(u).eq('id',id).select().single();if(e)throw e;return d;}
export async function deleteGeofence(id:string){const{e}=await supabase.from('child_geofences').delete().eq('id',id);if(e)throw e;}
export async function triggerSOS(childId:string,instId:string,lat?:number,lng?:number,reason?:string){const{d,e}=await supabase.from('child_sos_logs').insert({child_id:childId,institution_id:instId,triggered_by:'child',lat,lng,reason,status:'active'}).select().single();if(e)throw e;return d;}
export async function getSOSLogs(instId:string,opts?:{childId?:string;status?:string;limit?:number}){let q=supabase.from('child_sos_logs').select('*,child:education_students(full_name)').eq('institution_id',instId).order('created_at',{ascending:false});if(opts?.childId)q=q.eq('child_id',opts.childId);if(opts?.status)q=q.eq('status',opts.status);if(opts?.limit)q=q.limit(opts.limit);const{d,e}=await q;if(e)throw e;return d||[];}
export async function resolveSOS(sosId:string,notes:string,resolverId:string){const{d,e}=await supabase.from('child_sos_logs').update({status:'resolved',resolved_by:resolverId,resolved_at:new Date().toISOString(),resolution_notes:notes}).eq('id',sosId).select().single();if(e)throw e;return d;}
export async function getEmergencyContacts(childId:string){const{d,e}=await supabase.from('child_emergency_contacts').select('*').eq('child_id',childId).order('priority',{ascending:true});if(e)throw e;return d||[];}
export async function addEmergencyContact(c:Omit<EC,'id'|'created_at'>){const{d,e}=await supabase.from('child_emergency_contacts').insert(c).select().single();if(e)throw e;return d;}
export async function updateEmergencyContact(id:string,u:Partial<EC>){const{d,e}=await supabase.from('child_emergency_contacts').update(u).eq('id',id).select().single();if(e)throw e;return d;}
export async function deleteEmergencyContact(id:string){const{e}=await supabase.from('child_emergency_contacts').delete().eq('id',id);if(e)throw e;}
export async function getIncidents(instId:string,opts?:{childId?:string;status?:string;severity?:string}){let q=supabase.from('child_safety_incidents').select('*,child:education_students(full_name)').eq('institution_id',instId).order('created_at',{ascending:false});if(opts?.childId)q=q.eq('child_id',opts.childId);if(opts?.status)q=q.eq('status',opts.status);if(opts?.severity)q=q.eq('severity',opts.severity);const{d,e}=await q;if(e)throw e;return d||[];}
export async function createIncident(i:Omit<INC,'id'|'created_at'|'updated_at'>){const{d,e}=await supabase.from('child_safety_incidents').insert(i).select().single();if(e)throw e;return d;}
export async function updateIncident(id:string,u:Partial<INC>){const{d,e}=await supabase.from('child_safety_incidents').update(u).eq('id',id).select().single();if(e)throw e;return d;}
export async function getSafetyDashboard(instId:string){const[{data:a},{data:b},{data:c},{data:t}]=await Promise.all([supabase.from('child_sos_logs').select('id').eq('institution_id',instId).eq('status','active'),supabase.from('child_safety_incidents').select('id').eq('institution_id',instId).eq('status','open'),supabase.from('child_safety_incidents').select('id').eq('institution_id',instId).eq('severity','critical').eq('status','open'),supabase.from('child_sos_logs').select('id').eq('institution_id',instId).gte('created_at',new Date().toISOString().split('T')[0])]);return{activeSOS:a?.length||0,openIncidents:b?.length||0,criticalIncidents:c?.length||0,todaySOS:t?.length||0};}
