import { AppManifest } from '@/types/module.types';

export const garageManifest: AppManifest = {
  id: 'garage',
  name: 'Garage OS',
  version: '2.0.0',
  entry_point: '/(garage)',
  icon: '🔧',
  color: '#3B82F6',
  system_app: false,
  installable: true,
  enabled: true,
  permissions: ['location', 'camera', 'notifications', ],
  routes: ['/onboarding', '/dashboard', '/diagnostics', '/appointments', '/inventory', '/fleet', '/customer'],
  dependencies: ['wallet', 'health'],
  description: 'Full garage management: OBD-II diagnostics, work orders, inventory, fleet, and customer portal.',
  developer: 'MTAA OS',
  size: '24 MB',
  rating: 4.8,
  reviews: 1240,
  features: [
    'OBD-II Diagnostics & ECU Programming',
    'Work Order Management',
    'Inventory & Parts Tracking',
    'Fleet Management',
    'Customer Portal & Ratings',
    'Digital Vehicle Passport',
    'Roadworthy & Compliance',
    'Insurance Claims Integration',
  ],
  isSystemApp: false,
  isLocalApp: true,
};
