import { AppManifest } from '../types';

export const civicManifest: AppManifest = {
  id: 'civic',
  name: 'Civic Services',
  description: 'Government services: Police, Courts, Prisons, and Public Records',
  version: '1.0.0',
  category: 'civic',
  icon: 'shield',
  color: '#1E40AF',
  author: 'MTAA OS',
  size: '45MB',
  rating: 4.8,
  installs: 0,
  isOSBased: false,
  entryPoint: '/(os)/civic',
  permissions: ['location', 'camera', 'storage', 'notifications'],
  screens: [
    { route: '/(os)/civic', label: 'Civic Hub', icon: 'shield' },
    { route: '/(os)/civic/police', label: 'Police', icon: 'shield' },
    { route: '/(os)/civic/police/cases', label: 'Cases', icon: 'file-text' },
    { route: '/(os)/civic/police/officers', label: 'Officers', icon: 'users' },
    { route: '/(os)/civic/courts', label: 'Courts', icon: 'scale' },
    { route: '/(os)/civic/courts/cases', label: 'Court Cases', icon: 'gavel' },
    { route: '/(os)/civic/courts/hearings', label: 'Hearings', icon: 'mic' },
    { route: '/(os)/civic/courts/judgments', label: 'Judgments', icon: 'check-circle' },
    { route: '/(os)/civic/courts/bails', label: 'Bails', icon: 'unlock' },
    { route: '/(os)/civic/courts/fines', label: 'Fines', icon: 'dollar-sign' },
    { route: '/(os)/civic/courts/appeals', label: 'Appeals', icon: 'repeat' },
    { route: '/(os)/civic/courts/jury', label: 'Jury', icon: 'users' },
    { route: '/(os)/civic/prisons', label: 'Prisons', icon: 'lock' },
    { route: '/(os)/civic/prisons/inmates', label: 'Inmates', icon: 'user' },
    { route: '/(os)/civic/prisons/cells', label: 'Cells', icon: 'grid' },
    { route: '/(os)/civic/prisons/visits', label: 'Visits', icon: 'user-check' },
    { route: '/(os)/civic/prisons/incidents', label: 'Incidents', icon: 'alert-triangle' },
    { route: '/(os)/civic/prisons/movements', label: 'Movements', icon: 'arrow-right' },
    { route: '/(os)/civic/prisons/parole', label: 'Parole', icon: 'user-plus' },
    { route: '/(os)/civic/prisons/wardens', label: 'Wardens', icon: 'user-check' },
  ],
  features: [
    'Police case reporting and tracking',
    'Court case management and scheduling',
    'Hearing calendar and jury management',
    'Bail and fine processing',
    'Appeals workflow',
    'Inmate records and cell management',
    'Visit scheduling and tracking',
    'Incident reporting and parole reviews',
  ],
  minOSVersion: '1.0.0',
  supportedPlatforms: ['ios', 'android', 'web'],
  requiresAuth: true,
  hasInAppPurchases: false,
  dataUsage: 'medium',
  offlineSupport: false,
};
