import { supabase } from '@/lib/supabase';
export async function getDoctorDashboard(doctorId: string) { const { data, error } = await supabase.from('health_practitioners').select('*').eq('id', doctorId).single(); if (error) throw error; return data; }
export async function getTodayAppointments(doctorId: string, range: { from: number; to: number }) { const today = new Date().toISOString().split('T')[0]; const { data, error } = await supabase.from('health_appointments').select('*').eq('practitioner_id', doctorId).gte('scheduled_date', today).lt('scheduled_date', today + 'T23:59:59').range(range.from, range.to); if (error) throw error; return data || []; }
export async function getPendingOrders(doctorId: string, range: { from: number; to: number }) { const { data, error } = await supabase.from('health_orders').select('*').eq('practitioner_id', doctorId).eq('status', 'pending').range(range.from, range.to); if (error) throw error; return data || []; }
export async function createPrescription(payload: any) { const { data, error } = await supabase.from('health_prescriptions').insert(payload).select().single(); if (error) throw error; return data; }
export async function getDoctorOrders(doctorId: string, range: { from: number; to: number }) { const { data, error } = await supabase.from('health_orders').select('*').eq('practitioner_id', doctorId).range(range.from, range.to); if (error) throw error; return data || []; }
export async function getFollowUps(doctorId: string, range: { from: number; to: number }) { const { data, error } = await supabase.from('health_follow_ups').select('*').eq('practitioner_id', doctorId).range(range.from, range.to); if (error) throw error; return data || []; }
export async function getLabOrders(doctorId: string, range: { from: number; to: number }) { const { data, error } = await supabase.from('health_lab_orders').select('*').eq('ordered_by', doctorId).range(range.from, range.to); if (error) throw error; return data || []; }
export async function getDoctorNotes(doctorId: string, filter?: string, range?: { from: number; to: number }) { let query = supabase.from('health_clinical_notes').select('*').eq('author_id', doctorId); if (filter) query = query.ilike('title', `%${filter}%`); if (range) query = query.range(range.from, range.to); const { data, error } = await query; if (error) throw error; return data || []; }
export async function createNote(payload: any) { const { data, error } = await supabase.from('health_clinical_notes').insert(payload).select().single(); if (error) throw error; return data; }
export async function signNote(noteId: string, signature: string) { const { data, error } = await supabase.from('health_clinical_notes').update({ signed_by: signature, signed_at: new Date().toISOString() }).eq('id', noteId).select().single(); if (error) throw error; return data; }
