export default {
  id: 'streets',
  name: 'MTAA Streets',
  description: 'Social feed, livestreams, marketplace, jobs, and creator tools',
  version: '1.0.0',
  icon: 'streets-icon',
  color: '#E91E63',
  category: 'social',
  screens: [
    { route: '(tabs)/feed', title: 'Feed', icon: 'home' },
    { route: '(tabs)/discover', title: 'Discover', icon: 'search' },
    { route: '(tabs)/create', title: 'Create', icon: 'plus-circle' },
    { route: '(tabs)/inbox', title: 'Inbox', icon: 'message-circle' },
    { route: '(tabs)/profile', title: 'Profile', icon: 'user' },
    { route: 'comments/[postId]', title: 'Comments', modal: true },
    { route: 'share/[postId]', title: 'Share', modal: true },
    { route: 'live/[streamId]', title: 'Live', fullScreen: true },
    { route: 'settings', title: 'Settings' },
    { route: 'wallet', title: 'Wallet' },
    { route: 'shop', title: 'Shop' },
    { route: 'jobs', title: 'Jobs' },
    { route: 'creator', title: 'Creator Dashboard' },
    { route: 'ads', title: 'Promote' },
  ],
  dependencies: ['wallet', 'shop', 'jobs', 'marketplace'],
  permissions: ['camera', 'microphone', 'photo_library', 'notifications'],
  features: [
    'feed_scroll',
    'video_player',
    'live_streaming',
    'comments_nested',
    'share_native',
    'wallet_tips',
    'creator_monetization',
    'ads_self_serve',
  ],
};
